### ISSUE TITLE
ошибка при запуске  TypeError: Cannot read property 'A' of undefined

### ISSUE THREAD

**Issue by tsvetkovpro** [isuvorov/lego-starter-kit#2]
Как можно убрать ошибку при запуске проекта? 

![image](https://cloud.githubusercontent.com/assets/2004857/20637777/73661116-b3b3-11e6-84de-6c74f87aabbd.png)

**Comment by aliomaster** [comment]
Плюсуюсь, та же ошибка

**Comment by Yukioru** [comment]
Данный баг был исправлен. Компонент **A** и другие теперь находятся в [lsk-general](https://github.com/isuvorov/lsk-general)

**Comment by isuvorov** [comment]
Многие спрашивают, что такое за компонент **< A >**  и для чего он нужен. Решил прояснять некоторые моменты:

В [lsk-general](github.com/isuvovov/lsk-general) существуют 2 компонента:

**Link** - это span, при клик на который ищется history в контексте и если находится - то делается редирект, через этот history.push(), нужно для того, чтобы была html5 история переходов, без перерендеринга страницы
Примерно аналогичные компоненты есть:

-  [react-starter-kit](https://github.com/kriasoft/react-starter-kit/tree/35b7c774f084a5f46fe185d93f06f3123b815d25/src/components/Link) 
- [react-router](https://github.com/ReactTraining/react-router/blob/21e4a1e95c4e9e8da534088b2d74157bf8f62ac4/modules/Link.js)

**A** - это тот же Link, только обернутый в тег <a>, 
делает тоже самое, вместо нативного href, делает переход по history.push(), однако сам href в html артибуте оставляет, нужно это для того, чтобы работала "правая кнопка мыши > открыть в новой вкладке "

Помимо этого, наш компонент <А> - позволяет раскрашивать такие ссылки в корпоративные цвета, не руша блоковую концепцию БЭМ. Подход также позволяет в дальнейшем просто заменить переменную в PostCSS, чтобы перекрасить все подобные ссылки.

P.S.
по БЭМ использовать глобальные стили для a, a:visited, a:hover - не хорошо
так как теги <a> - это могут быть не только контекстные ссылки, но и какие-то другие элементы (меню, логотип)
